# Generated by Django 5.0.6 on 2024-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='idea_images/no_idea.jpg', upload_to='idea_images/'),
        ),
    ]
