# Generated by Django 5.0.6 on 2024-07-26 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_favourite'),
        ('investment', '0001_initial'),
        ('partnership', '0003_precoauthor_is_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='co_author',
            field=models.ManyToManyField(blank=True, related_name='coauthored_ideas', through='partnership.CoAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='investors_ideas', through='investment.Investor', to=settings.AUTH_USER_MODEL),
        ),
    ]
