version: "3.9"

services:
  pg_brainwave:
    image: postgres
    container_name: brainwave_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  django_brainwave:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: brainwave_django
    depends_on:
      - pg_brainwave
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    command: bash -c "./run_all.sh"

  nginx_brainwave:
      image: nginx
      container_name: brainwave_nginx
      volumes:
        - static_volume:/app/static
        - media_volume:/app/media
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - django_brainwave
      ports:
        - "${NGINX_EXTERNAL_PORT}:80"


  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672


volumes:
  static_volume:
  media_volume:
  db-data:


# Если рассматривать запуск всех связанных приложений через docker compose
# 1. postgres
# 2. django-backend + gunicorn (uwsgi) - celery
# 3. nginx (apache)
# 4. celery





