# Generated by Django 5.0.6 on 2024-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_precoauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoauthor',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
