# Generated by Django 5.0.6 on 2024-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/idea_images/non_category.jpg', upload_to='idea_images'),
        ),
    ]
