# Generated by Django 5.0.6 on 2024-07-04 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea', '0007_idea_co_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_type', models.CharField(choices=[('shares', 'Shares'), ('debt', 'Debt'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
