# Generated by Django 5.0.6 on 2024-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_avatars/no_avatar.png', upload_to='user_avatars/'),
        ),
    ]
