# Generated by Django 5.0.6 on 2024-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='idea',
        ),
        migrations.AddField(
            model_name='comment',
            name='idea',
            field=models.ManyToManyField(to='idea.idea'),
        ),
    ]
