# Generated by Django 5.0.6 on 2024-06-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('idea', '0002_idea_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='idea.idea'),
        ),
    ]
